### ISSUE TITLE
ScopeContext#destroy never called on purpose ?

### ISSUE THREAD

**Issue by sgalles** [tomitribe/microscoped#1]
First I want to say that I find your examples extremely informative. Thanks for this. 
I'm currently in the process of learning more about CDI Scopes and it is very useful.

That being said I'm a bit confused by something : is this on purpose that `ScopeContext#destroy` is never called in your code ? I had the feeling that it should be called here https://github.com/tomitribe/microscoped/blob/master/microscoped-core/src/main/java/org/tomitribe/microscoped/core/ScopeContext.java#L73

WDYT ?

**Comment by johnament** [comment]
Hi @sgalles each of these scopes are pseudo application scopes.  They last essentially for the duration of the server runtime.  New contexts are added, but never destroyed.

If you had a context that was say the duration of a TCP connection, then yes you would want a destroy.

**Comment by sgalles** [comment]
Hi @johnament , 
Ah ! It makes sense.
Thank you for your help.
